# Generated by Django 5.2.1 on 2025-05-23 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowhistory',
            name='userAdmin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administered_borrowings', to=settings.AUTH_USER_MODEL, verbose_name='Админ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
