# Generated by Django 5.2.1 on 2025-05-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_borrowhistory_useradmin_alter_borrowhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Выдана'), ('rejected', 'Отказано'), ('in_queue', 'В очереди'), ('returned', 'Возвращена')], default='pending', max_length=20),
        ),
    ]
