# Generated by Django 5.2.1 on 2025-05-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Выдана'), ('in_queue', 'В очереди')], default='pending', max_length=20),
        ),
    ]
