# Generated by Django 5.2.1 on 2025-05-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowhistory',
            name='adminAction',
            field=models.CharField(choices=[('refused', 'Отказано'), ('approved', 'Выдана'), ('returned', 'Возвращена')], default='approved', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата взятия'),
        ),
    ]
