# Generated by Django 5.2.1 on 2025-05-24 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_borrowhistory_due_back'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='copy',
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Books.book', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='adminAction',
            field=models.CharField(choices=[('refused', 'Отказано'), ('approved', 'Выдана'), ('returned', 'Возвращена')], max_length=20, verbose_name='Действие Админа'),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата одобрение/отказа'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='due_back',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая дата возврата'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Выдана'), ('in_queue', 'В очереди')], default='in_queue', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
